# Generated by Django 5.0.3 on 2024-03-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0004_category_alter_listing_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='commute',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_photo',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pet_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='school_district',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
