# Generated by Django 5.0.3 on 2024-03-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0005_listing_commute_listing_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='town',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('DAY', 'Dayton'), ('CNG', 'Cincinnati'), ('CMH', 'Columbus'), ('MCE', 'Mason')], default='DAY', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
