# Generated by Django 5.0.3 on 2024-03-31 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0006_listing_town_alter_listing_city_alter_listing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('agree_termsConditions', models.BooleanField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp.customer')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp.listing')),
            ],
        ),
    ]
